services:
  # Container của gateway - gán cứng vào CPU Core 0
  gateway:
    build:
      context: ./gateway
    ports:
      - "8080:8080"
    cpuset: "0"
    environment:
      - GOGC=500
    depends_on:
      - pdu-session-1
      - pdu-session-2
      - pdu-session-3
      - pdu-session-4

  # Instance PDU Session 1
  pdu-session-1:
    build:
      context: ./pdu-session
    environment:
      - INSTANCE_ID=pdu-session-1
      - PORT=9001
    networks:
      default:
        aliases:
          - pdu-session

  # Instance PDU Session 2
  pdu-session-2:
    build:
      context: ./pdu-session
    environment:
      - INSTANCE_ID=pdu-session-2
      - PORT=9001
    networks:
      default:
        aliases:
          - pdu-session

  # Instance PDU Session 3
  pdu-session-3:
    build:
      context: ./pdu-session
    environment:
      - INSTANCE_ID=pdu-session-3
      - PORT=9001
    networks:
      default:
        aliases:
          - pdu-session

  # Instance PDU Session 4
  pdu-session-4:
    build:
      context: ./pdu-session
    environment:
      - INSTANCE_ID=pdu-session-4
      - PORT=9001
    networks:
      default:
        aliases:
          - pdu-session

  auto-request:
    build:
      context: ./auto-request
    environment:
      - TARGET_URL=http://gateway:8080/nsmf-pdusession/v1/sm-contexts
    depends_on:
      - gateway